Feat: Added smui to storbook, created styles for multiple button types
DecisiveAI/mdai-core-ui-system pull request #10
Opened 2024-11-21 18:25 UTC by shalane-proctor

2024-11-26 15:11 UTC, decisiveJoe commented on src/stories/button/Button.svelte
> +  $: classes = ['storybook-button', `storybook-button--${size}`, mode, isDisabled].join(' ');
instead of `storybook-button` how about `mdai-button`?

2024-11-26 15:15 UTC, decisiveJoe commented on src/stories/button/button.css
> +  background-color: #E288F6;
We should align on a method for overwriting the SMUI styles. I really liked the method of redeclaring the SMUI variables in `styles/mdai-bace.css` because it allowed me to ignore a lot of the super finnicky selectors.

I'll admit that approach puts the styles in a location that is not conveniently located next to the component.

Doesn't SMUI allow a custom theme? Could we use that, or is it not flexible enough for our needs?

2024-11-26 15:17 UTC, decisiveJoe commented on src/stories/button/Button.svelte
> +  $: isDisabled = disabled ? (primary ? 'storybook-button-primary--disabled' : 'storybook-button--disabled') : '';
Have you heard of the [classnames](https://github.com/JedWatson/classnames) helper package? It's pretty light and might be able to help with some of the dynamic classes you're dealing with here.

2024-11-26 15:39 UTC, decisiveJoe requested changes
Until we remove the boilerplate, can you add `storybook-static/` to your .gitignore I don't think we need to track those files just yet.

To keep a clear distinction between our work and the boilerplate stuff, can you move the components you worked on to `src/` e.g. `src/button`

Can you refactor your component prop declarations to match the Svelte 5 convention(s)? You can use the Switch component as an example. Though it would be nice to see if there's a way for the JSDoc comments to still come through in the stories

2024-11-27 04:17 UTC, shalane-proctor commented
@decisiveJoe Seems like there is still some weirdnesses with TS, $props, and storybook. The card has some errors, but seems similar to the TS issues on button.

2024-11-27 15:35 UTC, decisiveJoe commented on .gitignore
> +storybook-static/
weird. I would've thought this would have removed everything in the named directory from your PR 🤔

2024-11-27 15:37 UTC, decisiveJoe commented on src/theme/_smui-theme.scss
> +  $secondary: #6f6f6f,
Did making this change have any impact on the way the SMUI components render by default?

Asking b/c if it does what I think it's supposed to, maybe we can get rid of some of the overrides?

2024-11-27 15:44 UTC, decisiveJoe commented on src/button/Button.svelte
> +        variant?: 'default' | 'outlined' | 'raised';
Can you alias these so they match the labels in the figma?
```
  variant?: 'filled' | 'outlined' | 'text'
  ...
  ...
  const buttonModeAliasMap = {
  filled: 'raised',
  outlined: 'outlined',
  text: 'default'
}
...
let mode = $derived(buttonModeAliasMap[variant] || 'filled')
```

2024-11-27 15:46 UTC, decisiveJoe commented on src/button/Button.svelte
> +        backgroundColor?: string | undefined;
Do we need to support a backgroundColor prop? IMO it's counter to creating the component library

2024-11-27 15:46 UTC, decisiveJoe commented on src/button/Button.svelte
> +        square?: boolean;
Without "squarcle" buttons in the figma components, I don't think it should be reflected here.

2024-11-27 15:47 UTC, decisiveJoe commented on package.json
> +    "@mdi/js": "^7.4.47",
What's this dep doing for us?

2024-11-27 15:49 UTC, decisiveJoe commented on src/card/Card.svelte
> +    });
leftover console.log ;)

2024-11-27 16:07 UTC, shalane-proctor commented on .gitignore
> +storybook-static/
🤷🏻‍♀️

2024-11-27 16:07 UTC, shalane-proctor commented on package.json
> +    "@mdi/js": "^7.4.47",
Icons

2024-11-27 16:12 UTC, shalane-proctor commented on src/button/Button.svelte
> +        backgroundColor?: string | undefined;
This is fair.

2024-12-02 17:57 UTC, shalane-proctor commented on src/theme/_smui-theme.scss
> +  $secondary: #6f6f6f,
Don't remember if I ever responded to this anywhere. Sort of, tried adding a custom "$outlined" to this, but caused errors and didn't not work as expected. There may be a way to do some of the override stuff, but this did change the defaults of some things, yes.

2024-12-02 19:00 UTC, decisiveJoe commented on src/button/Button.svelte
> +    let mode = $derived(variant === 'Text' ? '' : buttonModeAliasMap[variant]);
In the storybook story for the Text button, it's showing up as the Filled. I think this line needs to account for `variant === undefined`. Perhaps this could also be pulled into a function?

2024-12-02 19:01 UTC, decisiveJoe commented on src/card/Card.svelte
> +      <Button variant='Filled' label={buttonLabels} disabled={buttonDisabled}></Button>
How does the consumer of the Card component indicate what the buttons _do_?

2024-12-02 19:01 UTC, decisiveJoe commented on src/button/Button.svelte
>    type ButtonProps = {
I just realized the Button should have an `onClick` prop too

2024-12-02 19:08 UTC, shalane-proctor commented on src/card/Card.svelte
> +    let style = $derived(variant === 'Primary' ? 'background-color: transparent;' : (variant === 'Outlined' ? 'border: 1px solid #393939; background-color: transparent' : 'background-color: #313131')
Do you have a reason for this? This seems like a bit of unnecessary code to me personally. I can, but I'm curious your reasoning.

2024-12-02 19:11 UTC, decisiveJoe commented on src/card/Card.svelte
> +    let style = $derived(variant === 'Primary' ? 'background-color: transparent;' : (variant === 'Outlined' ? 'border: 1px solid #393939; background-color: transparent' : 'background-color: #313131')
Nested ternaries require an amount of cognitive load to figure out what they're doing. Extracting the logic to a well named function makes it easier to understand what the line of code is trying to do.

Further, extracting it into a function means the entire style string can be determined in one place instead of background color determined here and also a width declaration in the markup.

2024-12-02 19:19 UTC, shalane-proctor commented on src/button/Button.svelte
> +    let mode = $derived(variant === 'Text' ? '' : buttonModeAliasMap[variant]);
Accidentally had a default value on props, so removing this fixed the issue since it was working on the form button. I feel that a function would just be unnecessary here too.

2024-12-02 19:19 UTC, shalane-proctor commented on src/card/Card.svelte
> +      <Button variant='Filled' label={buttonLabels} disabled={buttonDisabled}></Button>
Ooooops

2024-12-02 21:42 UTC, decisiveJoe approved these changes

2024-12-02 21:43 UTC, merged